version: "3"
services:
nginix:
restart: always
build:
dockerfile: Dockerfile
context: ./nginix
ports:
-"3080:80"
depends_on:
-nodeserver
-client
nodeserver:
restart: always
build:
dockerfile: Dockerfile.dev
context: ./server/
volumes:
-/app/node_modules
- ./server:/app
environment:
ports:
-"4000:4000"

client: