FROM node:alpine

WORKDIR ~/app

COPY package*.json ./

RUN npm i --silent

COPY . .
# ENV MONGO_URL= mongodb+srv://HariniThandoju:yin2uFwv8pilCEHg@zomato-master.wca14.mongodb.net/Zomato?retryWrites=true&w=majority
# ENV GOOGLE_CLIENT_ID=914751456229-6qd4h849o0pvum7hoal78eaeuslkhg8q.apps.googleusercontent.com
# ENV GOOGLE_CLIENT_SECRET=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
# ENV AWS_S3_ACCESS_KEY=AKIARCT2EXVNE3YRGUEJ
# ENV AWS_S3_SECRET_KEY=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
# ENV PORT=4000

CMD ["npm", "run", "dev"]